### PR TITLE
Drawer: change Edit Profile to Profile  Issue #32

### PR DESCRIPTION
**Pull request by SylviaMakuch**
Small change going from "Edit Profile" to "Profile"

### CODE REVIEW

**Comment by SylviaMakuch** [comment]
Issue: https://github.com/own-me/frontend/issues/38

**Comment by SylviaMakuch** [comment]
Revised
Screen Shot 2022-04-23 at 4 59 20 PM

**Review by ChristopherTrimboli — CHANGES_REQUESTED** [review]
Found this issue:

image

**Comment by ChristopherTrimboli** [comment]
PR does not make sense anymore, too old, closing.

**Pull request closed without merging**
