### PR TITLE
ui improvement

### PR DESCRIPTION
**Pull request by imWayneWY**

### CODE REVIEW

**Comment by ChristopherTrimboli** [comment]
you are apart of Organization, feel free to just make a branch, I think is simpler and gives better commit history

**Comment by imWayneWY** [comment]
> you are apart of Organization, feel free to just make a branch, I think is simpler and gives better commit history

I don't know why but I tried and was told that I don't have permission

**Comment by ChristopherTrimboli** [comment]
> > you are apart of Organization, feel free to just make a branch, I think is simpler and gives better commit history
> 
> I don't know why but I tried and was told that I don't have permission

my bad... invited you, should be able to do everything now

**Comment by ChristopherTrimboli** [comment]
don't need right now, I fixed a different way, but thanks :)

**Pull request closed without merging**
