### PR TITLE
NUDE_SWAP UI

### PR DESCRIPTION
**Pull request by SylviaMakuch**
Still Required (to-do)

- Cryptocurrency Icons on the drop-down 
- Connecting to smart contract

### CODE REVIEW

**Comment by SylviaMakuch** [comment]
Web/Mobile responsive and functional app

Still required:
- connection to wallet

**Review by ChristopherTrimboli — CHANGES_REQUESTED** [review]
Seeing some weird layout issues on desktop: 
image

**Comment by ChristopherTrimboli** [comment]
I fixed it up :) 

Screenshot 2022-06-12 202410

image

**Review by ChristopherTrimboli — APPROVED** [review]
looks amazing, this is big step for NUDESWAP

**Pull request merged**
